version: "3.9"

networks:
  appnet:

volumes:
  mysql_data:

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      
      - "8081:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
    depends_on:
      - mysql
      - redis
      - elasticsearch
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    environment:
      APP_ENV: local
      APP_URL: http://localhost:8081
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTIC_HOST: http://elasticsearch:9200
    networks:
      - appnet
    restart: unless-stopped

  worker:
    build:
      context: ./docker/php
    depends_on:
      - mysql
      - redis
    working_dir: /var/www/html
    command: sh -lc "php artisan queue:work --tries=3 --timeout=90"
    volumes:
      - ./laravel:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - appnet
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - appnet
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"     
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"                       
    networks:
      - appnet
    restart: unless-stopped

