version: "3.9"
services:
  api:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    image: registry.example.com/konovator/api:local
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    image: registry.example.com/konovator/web:local
    expose:
      - "80"
    depends_on:
      api:
        condition: service_started

  proxy:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      web:
        condition: service_started
      api:
        condition: service_started
